### ISSUE TITLE
News Sitemap getting blank page and giving error 500

### ISSUE THREAD

**Issue by pacoesni** [Yoast/wpseo-news#247]
### What did you expect to happen?

Showing the links for a News Sitemap at the 'yourdomain.com/news-sitemap.xml'
### What happened instead?

It shows a blank page. If you dig into the source code you will be able to see the links.
### How can we reproduce this behavior?

I'm just getting the error using the default setup of my server. GoGeek Siteground.
### Technical info
- WordPress version: 4.6
- Yoast SEO version: 3.5
- Yoast SEO: News version: 3.5

I looked into the code and found that the internal error 500 is related with 
`wpseo-news/classes/class-sitemap.php
`
Specifically, I looked at this section:
`header( $protocol . ' 200 OK', true, 200 );
`

I fix it changing this by:
`header( $protocol, true, 200 );
`
And all works OK.

**Comment by CarolineGeven** [comment]
hi @pacoesni, thanks for reporting this issue with us. Can you confirm if this issue is still relevant? And if so, are you getting an error or are you receiving a blank page?

**Comment by CarolineGeven** [comment]
Closing this due to lack of activity. If the issue still persists, please open a new issue with the relevant information.

**Comment by monbauza** [comment]
User of conversation #266446 experienced the same issue: _news-sitemap.xml_ shows a blank page because _news-sitemap.xsl_ returns a 500-error. See log errors below. This happens when all non-Yoast plugins are deactivated and the theme is set to Twenty Fifteen.

```
/news-sitemap.xsl
[Tue Nov 28 15:34:23.998771 2017] [core:error] [pid 8155:tid 140383373993728] [client 95.97.223.4:58236] malformed header from script 'index.php': Bad header: 200 OK
[Tue Nov 28 15:34:24.626565 2017] [core:error] [pid 8155:tid 140383373993728] [client 95.97.223.4:58236] malformed header from script 'index.php': Bad header: 200 OK
```

The user managed to fix the issue by editing `/wpseo-news/classes/class-sitemap.php` as @pacoesni did.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 266446 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 272963 when this conversation has been closed.

**Comment by stodorovic** [comment]
I just found duplicate of this issue in Yoast SEO issues. It's possible that _short_open_tag_ is on and php parse xsl file as PHP code. It's simple fix replacing _include_ with _readfile_.
```
$ php -n -d short_open_tag=on xml-news-sitemap.xsl 
Parse error: syntax error, unexpected 'version' (T_STRING) in .../xml-news-sitemap.xsl on line 1
```

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 449084 when this conversation has been closed.

**Comment by archon810** [comment]
When can we expect a release (perhaps a hotfix one) for this?

**Comment by archon810** [comment]
Is this fixed in 9.3?

**Comment by archon810** [comment]
The fix will be in 9.8 as per support.

**Comment by ctibo** [comment]
I still have a an error 500 when using the plugin my server (wpseo-news, v12.6). 
The issue comes from here : 
```php
// yoast-news-seo/classes/sitemap.php
// public function build_news_sitemap_xsl()

if ( filter_input( INPUT_SERVER, 'SERVER_PROTOCOL' ) !== '' ) {
    $protocol = sanitize_text_field( filter_input( INPUT_SERVER, 'SERVER_PROTOCOL' ) );
}
```
`filter_input( INPUT_SERVER, 'SERVER_PROTOCOL' )` returns `NULL` on my setup.
I googled around and it seems that filter_input doesn't work when using FastCGI.

https://stackoverflow.com/a/36205923
`filter_input() doesn't work with INPUT_SERVER or INPUT_ENV when you use FASTCGI`

Could you «hard code» the protocol, as it is in the main Wordpress-SEO plugin ?

**Comment by Pcosta88** [comment]
@ctibo Hi, we would be happy to take a closer look at the issue you are having! Can you please send us an email to support@yoast.com? That way we can review the account and settings and if needed pass along the request to our developers.

**Comment by stodorovic** [comment]
@ctibo It's possible on unsupported PHP/Apache versions. It works (in my setup) on Apache 2.4/PHP 7.2. I think that works on supported LiteSpeed or Nginx. Which are your versions?

Possible solution could be function [wp_get_server_protocol](https://developer.wordpress.org/reference/functions/wp_get_server_protocol/) instead of filter_input.
