### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by stayallive** [Yoast/wpseo-news#601]
### What did you expect to happen?

Updating to Yoast SEO News 12.4 to not degrade performance.

### What happened instead?

It did.

### How can we reproduce this behavior?

Observe the changes in responsiveness. Potentially only on larger sites with many post types / tax combinations.

In our case `get_terms` is called +30k times every request compared to News 12.3:

![image](https://user-images.githubusercontent.com/1090754/72273328-748ac800-362a-11ea-883a-a643d41ee61a.png)

Looking at the callgraph the source is the new options class:

![image](https://user-images.githubusercontent.com/1090754/72273413-984e0e00-362a-11ea-877c-1ac87254da4a.png)

I really hope my suggestion for the performance improvements is not the cause of all this 😟 If there is more info I can provide please let me know! Happy to help get to the bottom of this.

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 12.8 (SEO News 12.4)

**Comment by Djennez** [comment]
Hi @stayallive and thanks for your report! We're already working on this as we've had multiple reports coming in. [This PR](https://github.com/Yoast/wpseo-news/pull/600) should fix this and we're planning to release this tomorrow (tuesday at around midday UTC+1).

I can't link this issue to a PR fixed-trigger anymore since it was already merged. So to prevent it from staying open too long I'm going to close it now. But please keep an eye out and test the patch of tomorrow. If the problems are not mitigated I'd really like to know, so you can leave a comment here.

**Comment by stayallive** [comment]
I didn’t even looked. Perfect! If it does not resolve it I’ll be back with more info. Thanks to everyone involved 💪

**Comment by Djennez** [comment]
Ah the reports were not via GitHub, so apart from the PR I don't think you could've known :) Better safe than sorry!

**Comment by Djennez** [comment]
@stayallive 12.4.1 has been released, please let us know if you're still running into issues.

**Comment by stayallive** [comment]
As far as we can tell it looks good 👍 thanks.

**Comment by Djennez** [comment]
Cool, thanks for the report and feedback!
